### ISSUE TITLE
npm run start error

### ISSUE THREAD

**Issue by benwturner** [varunshenoy/GraphGPT#15]
I get this when I try to start the app and reinstalling "debug" doesn't fix it.

node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/GraphGPT/node_modules/finalhandler/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (//GraphGPT/node_modules/finalhandler/index.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/GraphGPT/node_modules/finalhandler/node_modules/debug/package.json',
  requestPath: 'debug'
}

**Comment by iAmmarTahir** [comment]
Which npm and node version are you using?

**Comment by manmeet3591** [comment]
Similar error for me 

root@8cc416647c50:/GraphGPT# npm run start

> graphgpt@0.1.0 start /GraphGPT
> react-scripts start

/GraphGPT/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/GraphGPT/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphgpt@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the graphgpt@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-03T12_31_59_641Z-debug.log

**Comment by manmeet3591** [comment]
> Which npm and node version are you using?

@iAmmarTahir Which version will work ?

**Comment by iAmmarTahir** [comment]
I have these versions:
Node: v14.17.4
NPM: 7.9.1

**Comment by pomelo-nwu** [comment]
@manmeet3591 you should delete packages-lock.json and node_modules , and then npm install again
