### ISSUE TITLE
Error at first start - npm run start fails

### ISSUE THREAD

**Issue by lodm94** [varunshenoy/GraphGPT#18]
Hi, 
following your setup instructions, when i run the command `npm run start` i get the following error:

```
> graphgpt@0.1.0 start /mnt/c/Users/ldelmonte/Desktop/GraphGPT
> react-scripts start

/mnt/c/Users/ldelmonte/Desktop/GraphGPT/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Users/ldelmonte/Desktop/GraphGPT/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! graphgpt@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the graphgpt@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lodm/.npm/_logs/2023-02-02T14_52_59_897Z-debug.log
```

Any clue on this?

Thanks

**Comment by iAmmarTahir** [comment]
I have these versions: 
- Node: v14.17.4
- NPM: 7.9.1
and everything works fine for me. Can you try these specific versions?
